maintenance = false
key = ""
database {
    uri = "mongodb://localhost:27017"
    name = "Test Database"
}
messages {
    only-players-can-execute = "<red>Only players can execute this command.</red>"
    must-have-required-rank-or-higher = "<red>You need %requiredRank% or higher to use this command.</red>"
    available-instances-command-usage = "<red>Usage: %availableInstancesCommandUsage%</red>"
    available-instance = "<green>Available instances of type <yellow>%instanceTemplate%<green> are as follows:\n%availableInstances%"
    available-instance = "<green>%instanceName% <gray>[%instanceOnlinePlayerCount%/%instanceMaxPlayerCount%] <dark_gray>(%instanceConnectionAddress%:%instanceConnectionPort%)"
    chat-command-usage = "<red>Usage: %chatCommandUsage%</red>"
    chat-command-usage = "<red>Usage: %chatCommandUsage%"
    message-command-usage = "<red>Usage: %messageCommandUsage%"
    player-must-be-in-a-guild = "<red>You must be in a guild to use guild chat."
    player-must-be-in-a-party = "<red>You must be in a party to use party chat."
    insufficient-message-command-args = "<red>Usage: /chat message <player>"
    message-command-player-not-found = "<red>Player %targetPlayerName% was not found."
    message-command-this-player-has-ignored-you = "<red>You cannot message this player."
    chat-mode-set = "<green>Chat mode set to %chatMode%"
    guild-level-up-header = "<aqua><strikethrough>-----------------------------------------------------</strikethrough>"
    guild-level-up-message = "<yellow>Your guild has just reached <gold>Level %guildLevel%<yellow>!"
    guild-level-up-bottom-header = "<aqua><strikethrough>-----------------------------------------------------</strikethrough>"

    chat-mode-color {
        all = "<gold><bold>ALL</bold>"
        guild = "<dark_green><bold>GUILD</bold>"
        party = "<blue><bold>PARTY</bold>"
        message = "<light_purple><bold>MESSAGE</bold>"
    }
}